"""The tool catalog snapshot (V3-05, AGENT-ACCESS §6 "Contract tests", R-V3-20, R-V3-23).

``tools.snap.json`` pins the catalog as a client sees it, so any change to a
tool's name, description, annotations or schemas is a deliberate, reviewed
diff:

* ``tools``: every tool as ``tools/list`` returns it to a full-scope key
  (``*``) with the dial gate open, which is every declared tool. For each tool
  it pins the description, the annotations, the input schema, the output
  schema (shared by all tools, stored once under ``output_schema``) and
  ``_meta``. It also pins what the client cannot see, taken from the
  declarations:
  - ``scopes``: every scope the tool needs (the chat tools' three, R-V3-20);
  - ``kind``: which annotation preset the tool declares;
  - ``write_scopes`` and ``mixed``: a read tool's optional write path;
  - ``gate``: an extra registration predicate (``dial_enabled``, ``any_write``).
  Mixed tools also pin the annotations a Read-only key sees (R-V3-23 f).
* ``visible``: the tool list of each console preset (R-V3-9), of a full-scope
  key with and without the dial gate (R-V3-7), and of ``LKAP_MCP_READ_ONLY=1``.

Regenerate after an intended change, then review the diff::

    uv run pytest tests/test_catalog_snapshot.py --snapshot-update
"""

from __future__ import annotations

import json
from importlib.metadata import entry_points
from pathlib import Path
from typing import Any

import pytest
from conftest import BUILDER_SCOPES, OPERATOR_SCOPES, READ_ONLY_SCOPES
from mcp.types import ToolAnnotations

from lkap_mcp.catalog import declared_specs
from lkap_mcp.registry import DESTRUCTIVE, IDEMPOTENT_WRITE, READ, WRITE, ToolSpec

SNAPSHOT = Path(__file__).with_name("tools.snap.json")
UPDATE_HINT = "uv run pytest tests/test_catalog_snapshot.py --snapshot-update"
CHAT_TOOLS = ("chat_start", "chat_send", "chat_rewind", "chat_end")
MIXED_TOOLS = ("connection_fleet", "agent_versions", "agent_limits", "api_request")

_PRESETS: dict[str, ToolAnnotations] = {
    "read": READ,
    "write": WRITE,
    "idempotent_write": IDEMPOTENT_WRITE,
    "destructive": DESTRUCTIVE,
}


def _kind(spec: ToolSpec) -> str:
    for name, preset in _PRESETS.items():
        if spec.annotations == preset:
            return name
    return "custom"


def _dump(value: Any) -> Any:
    return value.model_dump(mode="json", by_alias=True, exclude_none=True)


async def _listed(mcp_session: Any, raw: str, **settings: Any) -> dict[str, Any]:
    async with mcp_session(raw, **settings) as mcp:
        return {tool.name: _dump(tool) for tool in (await mcp.session.list_tools()).tools}


async def build_snapshot(key: Any, mcp_session: Any) -> dict[str, Any]:
    """The catalog as a full-scope client sees it, plus the declared scopes, kinds and gates."""
    full = await key(["*"])
    async with mcp_session(full, allow_dial=True) as mcp:
        tools = {tool.name: _dump(tool) for tool in (await mcp.session.list_tools()).tools}
        instructions = mcp.server.instructions

    specs = {spec.name: spec for spec in declared_specs()}
    assert set(tools) == set(specs), "a full-scope key with the dial gate open sees every declared tool"

    output_schemas = {json.dumps(tool.get("outputSchema"), sort_keys=True) for tool in tools.values()}
    assert len(output_schemas) == 1, "every tool returns a ToolResult"
    shared_output = json.loads(output_schemas.pop())

    read_only_key = await key(READ_ONLY_SCOPES)
    read_only_view = await _listed(mcp_session, read_only_key)

    entries: dict[str, Any] = {}
    for name in sorted(tools):
        spec = specs[name]
        entry = {key_: value for key_, value in tools[name].items() if key_ not in {"name", "outputSchema"}}
        entry |= {
            "scopes": sorted(spec.scopes),
            "kind": _kind(spec),
            "mixed": spec.mixed,
            "write_scopes": sorted(spec.write_scopes),
            "gate": spec.gated_by.__name__ if spec.gated_by else None,
            "data": spec.data,
        }
        if spec.mixed and name in read_only_view:
            entry["annotations_without_write_scope"] = read_only_view[name].get("annotations")
        entries[name] = entry

    visible: dict[str, list[str]] = {"read_only": sorted(read_only_view)}
    for preset, scopes in (("builder", BUILDER_SCOPES), ("operator", OPERATOR_SCOPES)):
        visible[preset] = sorted(await _listed(mcp_session, await key(scopes)))
    visible["full_scope"] = sorted(await _listed(mcp_session, full))
    visible["full_scope_with_dial"] = sorted(tools)
    visible["full_scope_read_only_mode"] = sorted(await _listed(mcp_session, full, read_only=True))

    return {
        "_comment": f"Generated by tests/test_catalog_snapshot.py; regenerate with: {UPDATE_HINT}",
        "server": {"name": "lkap", "instructions": instructions},
        "output_schema": shared_output,
        "tools": entries,
        "visible": visible,
    }


def _render(snapshot: dict[str, Any]) -> str:
    return json.dumps(snapshot, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _describe_drift(stored: dict[str, Any], current: dict[str, Any]) -> str:
    old, new = stored.get("tools", {}), current["tools"]
    lines = [f"tools.snap.json is out of date; if the change is intended run: {UPDATE_HINT}"]
    if added := sorted(set(new) - set(old)):
        lines.append(f"added: {added}")
    if removed := sorted(set(old) - set(new)):
        lines.append(f"removed: {removed}")
    if changed := sorted(name for name in set(old) & set(new) if old[name] != new[name]):
        lines.append(f"changed: {changed}")
    for section in ("server", "output_schema", "visible"):
        if stored.get(section) != current[section]:
            lines.append(f"changed section: {section}")
    return "\n".join(lines)


@pytest.fixture
async def snapshot(key: Any, mcp_session: Any, request: pytest.FixtureRequest) -> dict[str, Any]:
    """The current catalog; written to ``tools.snap.json`` under ``--snapshot-update``."""
    current = await build_snapshot(key, mcp_session)
    if request.config.getoption("--snapshot-update"):
        SNAPSHOT.write_text(_render(current), encoding="utf-8")
    return current


async def test_catalog_snapshot_matches_tools_snap_json(snapshot: dict[str, Any]) -> None:
    assert SNAPSHOT.exists(), f"{SNAPSHOT.name} is missing; create it with: {UPDATE_HINT}"
    stored = json.loads(SNAPSHOT.read_text(encoding="utf-8"))

    assert stored == json.loads(_render(snapshot)), _describe_drift(stored, snapshot)


async def test_catalog_chat_tools_need_agents_write_sessions_write_and_connections_read(
    snapshot: dict[str, Any],
) -> None:
    # R-V3-20: the Builder preset or higher; never the Read-only preset.
    for name in CHAT_TOOLS:
        assert snapshot["tools"][name]["scopes"] == ["agents:write", "connections:read", "sessions:write"]
    assert not set(CHAT_TOOLS) & set(snapshot["visible"]["read_only"])
    assert set(CHAT_TOOLS) <= set(snapshot["visible"]["builder"])


async def test_catalog_mixed_tools_present_as_read_only_without_their_write_scope(
    snapshot: dict[str, Any],
) -> None:
    # R-V3-23 (f): truthful hints for what the key can do; the write path refuses with `forbidden`.
    mixed = sorted(name for name, entry in snapshot["tools"].items() if entry["mixed"])
    assert mixed == sorted(MIXED_TOOLS)
    for name in MIXED_TOOLS:
        entry = snapshot["tools"][name]
        assert entry["annotations"]["readOnlyHint"] is False
        assert entry["annotations_without_write_scope"]["readOnlyHint"] is True


async def test_catalog_dial_tools_exist_only_behind_both_gates(snapshot: dict[str, Any]) -> None:
    # R-V3-7: `calls:write` on the key and LKAP_MCP_ALLOW_DIAL=1 on the process.
    for name in ("call_place", "call_control"):
        entry = snapshot["tools"][name]
        assert (entry["scopes"], entry["gate"], entry["kind"]) == (
            ["calls:write"],
            "dial_enabled",
            "destructive",
        )
        assert name in snapshot["visible"]["full_scope_with_dial"]
        for view in ("read_only", "builder", "operator", "full_scope", "full_scope_read_only_mode"):
            assert name not in snapshot["visible"][view]


def test_packaging_lkap_mcp_console_script_runs_the_stdio_entry_point() -> None:
    from lkap_mcp.__main__ import main

    [script] = entry_points(group="console_scripts", name="lkap-mcp")

    assert script.value == "lkap_mcp.__main__:main"
    assert script.load() is main
