import { describe, expect, it } from "vitest";

import type { UiPatch, UiPatchOp, UiSnapshot } from "@/contracts/lkap-contracts";
import {
  applyBlocksOp,
  applyOp,
  blockPathSegments,
  emptyUiState,
  initialUiStateStore,
  normalizeUiState,
  uiStateReducer,
} from "@/lib/ui-state";

import parity from "./fixtures/block_patch_parity.json";

/**
 * V2-11 / asks #68: the browser reducer applies `/blocks/...` patches exactly
 * like the worker's `lkap_agent.ui.channel.apply_patch_op` (`_apply_tree_op`).
 *
 * `fixtures/block_patch_parity.json` is **generated by the agent's real
 * reducer** (`web/scripts/gen-block-patch-parity.py`, run in `agent/`): every
 * case's `expected` is what Python produced for the same ops on the same
 * start state, so a divergence on either side fails here.
 */
const SESSION = "sess-1";

function snapshot(seq: number, blocks: Record<string, unknown>): UiSnapshot {
  return { v: 1, type: "snapshot", seq, session_id: SESSION, state: { v: 2, blocks } };
}

function patch(seq: number, ops: UiPatchOp[]): UiPatch {
  return { v: 1, type: "patch", seq, session_id: SESSION, ops };
}

describe("block patch parity with the agent (generated vectors)", () => {
  for (const testCase of parity.cases) {
    it(testCase.name, () => {
      let state: unknown = normalizeUiState({ v: 2, blocks: structuredClone(parity.start) });
      for (const op of testCase.ops as UiPatchOp[]) state = applyOp(state, op);
      expect((state as { blocks: unknown }).blocks).toEqual(testCase.expected);
    });
  }

  it("never mutates the previous state", () => {
    const before = normalizeUiState({ v: 2, blocks: structuredClone(parity.start) });
    const frozen = JSON.stringify(before);
    for (const testCase of parity.cases) {
      let state: unknown = before;
      for (const op of testCase.ops as UiPatchOp[]) state = applyOp(state, op);
    }
    expect(JSON.stringify(before)).toBe(frozen);
  });
});

describe("blocks in the envelope (#68)", () => {
  it("emptyUiState and normalizeUiState carry blocks", () => {
    expect(emptyUiState().blocks).toEqual({});
    expect(normalizeUiState({ v: 1 }).blocks).toEqual({});
    expect(normalizeUiState({ v: 2, blocks: { a: { x: 1 } } }).blocks).toEqual({ a: { x: 1 } });
  });

  it("passes v through (the v2 worker sends 2) and defaults it to 2", () => {
    expect(normalizeUiState({ v: 1 }).v).toBe(1);
    expect(normalizeUiState({ v: 2 }).v).toBe(2);
    expect(normalizeUiState({}).v).toBe(2);
  });

  it("recognises only /blocks paths, dropping empty segments", () => {
    expect(blockPathSegments("/blocks/t/rows")).toEqual(["t", "rows"]);
    expect(blockPathSegments("/blocks")).toEqual([]);
    expect(blockPathSegments("//blocks//t")).toEqual(["t"]);
    expect(blockPathSegments("/custom/blocks")).toBeNull();
    expect(blockPathSegments("/notes")).toBeNull();
  });

  it("ignores non-set ops on the root", () => {
    const blocks = { a: {} };
    expect(applyBlocksOp(blocks, [], { op: "append", path: "/blocks", value: 1 })).toBe(blocks);
  });

  it("leaves the envelope fields alone", () => {
    const base = normalizeUiState({ v: 2, notes: [{ id: "n1", text: "x", kind: "note", tone: "neutral", ts: 1 }], blocks: {} });
    const next = applyOp(base, { op: "set", path: "/blocks/t", value: { rows: [] } }) as typeof base;
    expect(next.notes).toBe(base.notes);
    expect(next.blocks).toEqual({ t: { rows: [] } });
  });
});

describe("reducer: block snapshots and patches in seq order", () => {
  it("applies the seq-1 snapshot's blocks and the patches after it", () => {
    let store = uiStateReducer(initialUiStateStore(), {
      type: "message",
      message: snapshot(1, { intake: { schema: {}, values: {}, status: "idle", submitted_at: null } }),
    });
    expect(store.state.blocks).toEqual({ intake: { schema: {}, values: {}, status: "idle", submitted_at: null } });

    // `request_form`: the worker sets the whole block to "requested" with the prefill.
    store = uiStateReducer(store, {
      type: "message",
      message: patch(2, [
        {
          op: "set",
          path: "/blocks/intake",
          value: { schema: { type: "object", properties: {} }, values: { name: "Ada" }, status: "requested", submitted_at: null },
        },
      ]),
    });
    expect((store.state.blocks.intake as { status: string }).status).toBe("requested");

    // Form submit is one patch with three ops.
    store = uiStateReducer(store, {
      type: "message",
      message: patch(3, [
        { op: "set", path: "/blocks/intake/values", value: { name: "Ada Lovelace" } },
        { op: "set", path: "/blocks/intake/status", value: "submitted" },
        { op: "set", path: "/blocks/intake/submitted_at", value: 1777000000.5 },
      ]),
    });
    expect(store.state.blocks.intake).toEqual({
      schema: { type: "object", properties: {} },
      values: { name: "Ada Lovelace" },
      status: "submitted",
      submitted_at: 1777000000.5,
    });
    expect(store.seq).toBe(3);
  });

  it("appends a pinned frame to the gallery in the same patch as /assets", () => {
    let store = uiStateReducer(initialUiStateStore(), {
      type: "message",
      message: snapshot(1, { photos: { asset_ids: [], selected: null } }),
    });
    store = uiStateReducer(store, {
      type: "message",
      message: patch(2, [
        { op: "append", path: "/assets", value: { asset_id: "a1", kind: "photo", mime: "image/jpeg", ts: 1 } },
        { op: "append", path: "/blocks/photos/asset_ids", value: "a1" },
      ]),
    });
    expect(store.state.assets.map((a) => a.asset_id)).toEqual(["a1"]);
    expect(store.state.blocks.photos).toEqual({ asset_ids: ["a1"], selected: null });
  });

  it("a gap drops block patches until a resnapshot restores the block state", () => {
    let store = uiStateReducer(initialUiStateStore(), { type: "message", message: snapshot(1, { t: { rows: [] } }) });
    store = uiStateReducer(store, {
      type: "message",
      message: patch(3, [{ op: "append", path: "/blocks/t/rows", value: { id: "r1" } }]),
    });
    expect(store.needsSnapshot).toBe(true);
    expect(store.state.blocks.t).toEqual({ rows: [] });
    store = uiStateReducer(store, { type: "message", message: snapshot(3, { t: { rows: [{ id: "r1" }] } }) });
    expect(store.needsSnapshot).toBe(false);
    expect(store.state.blocks.t).toEqual({ rows: [{ id: "r1" }] });
  });
});
