#!/usr/bin/env python3
"""Generate `agent/requirements/{slim,full}.txt` from the provider registry.

Usage (needs `lkap_contracts` importable — run with any venv that has it,
e.g. the contracts package's own)::

    cd livekit_agent_platform
    contracts/.venv/bin/python scripts/gen_plugin_requirements.py          # write
    contracts/.venv/bin/python scripts/gen_plugin_requirements.py --check  # verify, no writes (CI)

or, equivalently, via uv from the contracts project::

    uv run --project contracts python ../scripts/gen_plugin_requirements.py

What it writes, per CONTRACTS-V2 §7 ("agent/requirements/{slim,full}.txt are
generated by scripts/gen_plugin_requirements.py from the registry
(worker_image field), pinned to the livekit-agents version lockstep, minus
availability in {incompatible, removed, deferred}"):

- `agent/requirements/slim.txt` / `full.txt`: one `livekit-plugins-*==<version>`
  line per package needed by that flavor's selected ids (see
  `check_installed_providers.selected_ids` — the single source of truth for
  *which ids*, shared with the import-check gate so the two can never drift).
  Bare vendor-SDK packages the registry also references (`openai`,
  `google-genai`) are deliberately **not** emitted: both are already base
  dependencies of `agent/pyproject.toml` (for the two `image_gen` providers)
  at their own version ranges, and `fastembed` / a plain `livekit-agents`
  line are skipped too — see the module docstring of
  `check_installed_providers.py` for why `embedding` providers are never
  installed into this image at all. Re-declaring an already-satisfied
  package here with a different pin risks fighting `agent/uv.lock`'s frozen
  resolution instead of layering cleanly on top of it (`agent/Dockerfile`).
- `agent/requirements/check_installed_providers.py`: a byte-identical mirror
  of this repo's `scripts/check_installed_providers.py`, because
  `agent/Dockerfile`'s build context is `agent/` only (deliberately, to
  match what `lk agent create`/`lk agent deploy` build from — see that
  Dockerfile's header) and so cannot `COPY` a repo-root script directly.

`--check` is the CI form (`contracts.yml`): exits non-zero and prints a diff
if any generated file would change, so a registry edit that is not
accompanied by regenerating these files fails the build.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
_ROOT = _SCRIPT_DIR.parent
_CONTRACTS_SRC = _ROOT / "contracts" / "src"
_AGENT_REQUIREMENTS_DIR = _ROOT / "agent" / "requirements"
_CHECKER_SRC = _SCRIPT_DIR / "check_installed_providers.py"
_CHECKER_MIRROR = _AGENT_REQUIREMENTS_DIR / "check_installed_providers.py"

#: Bare (non `livekit-plugins-*`) package names the registry references that
#: must NOT be emitted into the generated requirements files — see the
#: module docstring for why each is excluded.
_EXCLUDED_BARE_PACKAGES = frozenset({"livekit-agents", "openai", "google-genai", "fastembed", ""})

#: The livekit-agents release every plugin line is pinned to (lockstep with
#: `agent/pyproject.toml`; R-V4-53).
LIVEKIT_AGENTS_VERSION = "1.8.3"

#: Plugins whose release for this SDK line has a different version number
#: (R-V4-53): `livekit-plugins-bithuman` skipped 1.8.3 on PyPI, and its 1.8.4
#: (published with livekit-agents 1.8.3) requires `livekit-agents>=1.8.3`.
PLUGIN_VERSION_OVERRIDES: dict[str, str] = {"livekit-plugins-bithuman": "1.8.4"}

_HEADER = """\
# Generated by scripts/gen_plugin_requirements.py — DO NOT EDIT BY HAND.
#
# Source: contracts/src/lkap_contracts/providers.py REGISTRY, flavor={flavor}
# (CONTRACTS-V2 §7; ids selected by check_installed_providers.selected_ids,
# shared with the build-time import-check gate so this list and that gate
# can never drift). Regenerate after any registry change:
#
#   contracts/.venv/bin/python scripts/gen_plugin_requirements.py
#
# These are ADDITIONAL packages layered on top of agent/pyproject.toml's own
# livekit-agents=={version} baseline via `uv pip install -r` in agent/Dockerfile
# — they are not a replacement for `uv sync --frozen`. Bare vendor SDKs
# already declared as base deps (openai, google-genai) and API-only packages
# (fastembed, for embedding providers the worker never constructs — see
# check_installed_providers.py) are intentionally omitted; see
# docs/v2/CONTRACTS-V2.md §7 and docs/v2/_asks.md #32.
#
# Plugin pins follow livekit-agents=={version}; overrides (no release at that
# version on PyPI, same SDK line): {overrides}.
"""


def _load_registry_modules() -> tuple[object, object]:
    """Import `check_installed_providers` (this dir) and `lkap_contracts.providers`.

    Returns:
        ``(check_installed_providers module, providers module)``.
    """
    sys.path.insert(0, str(_SCRIPT_DIR))
    sys.path.insert(0, str(_CONTRACTS_SRC))
    import check_installed_providers as cip  # noqa: PLC0415
    from lkap_contracts import providers  # noqa: PLC0415

    return cip, providers


def packages_for_flavor(flavor: str) -> list[str]:
    """Return the sorted, deduplicated `livekit-plugins-*==<version>` lines for a flavor.

    Args:
        flavor: ``"slim"`` or ``"full"``.

    Returns:
        Sorted `"package==<version>"` requirement strings, pinned to
        `LIVEKIT_AGENTS_VERSION` unless `PLUGIN_VERSION_OVERRIDES` names the package.
    """
    cip, providers = _load_registry_modules()
    ids = cip.selected_ids(flavor)
    packages = set()
    for pid in ids:
        spec = providers.get(pid)
        if spec.package in _EXCLUDED_BARE_PACKAGES:
            continue
        packages.add(spec.package)
    assert "livekit-plugins-minimax" not in packages, (
        "livekit-plugins-minimax is availability='incompatible' and must never be installed "
        "(CONTRACTS-V2 §4.1 / D-V2-7); by_image() already filters non-'available' entries, so "
        "this indicates a registry regression, not a generator bug."
    )
    return [f"{pkg}=={PLUGIN_VERSION_OVERRIDES.get(pkg, LIVEKIT_AGENTS_VERSION)}" for pkg in sorted(packages)]


def render(flavor: str) -> str:
    """Render the full text of `requirements/{flavor}.txt`."""
    lines = packages_for_flavor(flavor)
    overrides = ", ".join(f"{pkg}=={ver}" for pkg, ver in sorted(PLUGIN_VERSION_OVERRIDES.items())) or "none"
    header = _HEADER.format(flavor=flavor, version=LIVEKIT_AGENTS_VERSION, overrides=overrides)
    return header + "\n".join(lines) + "\n"


def _check_or_write(path: Path, content: str, *, check: bool) -> bool:
    """Write `content` to `path`, or (in `--check` mode) compare without writing.

    Returns:
        True if `path` already matched `content` (or was written successfully
        in non-check mode); False if `--check` found a mismatch.
    """
    existing = path.read_text() if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"gen_plugin_requirements --check: {path} is stale (would change)", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"gen_plugin_requirements: wrote {path}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files match the registry without writing (CI mode).",
    )
    args = parser.parse_args(argv)

    ok = True
    for flavor in ("slim", "full"):
        content = render(flavor)
        target = _AGENT_REQUIREMENTS_DIR / f"{flavor}.txt"
        ok = _check_or_write(target, content, check=args.check) and ok

    # Mirror the canonical checker script verbatim (build-context trap: see
    # this module's docstring and check_installed_providers.py's own).
    mirror_content = _CHECKER_SRC.read_text()
    ok = _check_or_write(_CHECKER_MIRROR, mirror_content, check=args.check) and ok

    if args.check and not ok:
        print(
            "gen_plugin_requirements --check: FAILED — run "
            "`contracts/.venv/bin/python scripts/gen_plugin_requirements.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
